Updated test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,11 +1,13 @@
 name: Pull and Test
 
 on:
-    repository_dispatch:
-      types: [build]
+    workflow_run:
+        workflows: ['Build and Push Image']
+        types: 
+            - completed
 
 jobs:
-    test:
+    build:
         runs-on: ubuntu-latest
         steps:
             - 
@@ -23,9 +25,20 @@ jobs:
             -
              name: Pull image from registry
              run: |
-                docker pull ${{ secrets.DOCKERHUB_UNAME }}/local-builds:${{ github.event.client_payload.ref }}       
+                docker pull ${{ secrets.DOCKERHUB_UNAME }}/local-builds:latest
+            -
+             name: Run image and test
+             id: run_container
+             run: |
+                score=$(docker run ${{ secrets.DOCKERHUB_UNAME }}/local-builds:latest)
+                echo "::set-output name=score::$score"
             - 
-              name: Test image
-              run: |
-                docker run ${{ secrets.DOCKERHUB_UNAME }}/local-builds:${{ github.event.client_payload.ref }}
-            
+             name: Check score
+             run: |
+                score="${{ steps.run_container.outputs.score }}"
+                if (( $(echo "$score > 0.5" | bc -l) )); then
+                    echo "Score is greater than 0.5. Pipeline passes."
+                else
+                    echo "Score is less than or equal to 0.5. Pipeline fails."
+                    exit 1
+                fi
